apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: feature-deployment
  name: feature-service
  namespace: staging
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: feature-deployment
  type: ClusterIP
status:
  loadBalancer: {}
