apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: auth-service-entry
  name: auth-service-entry
spec:
  ports:
  - port: 8081
    protocol: TCP
    nodePort: 30001
  selector:
    app: auth-deployment
  type: NodePort
status:
  loadBalancer: {}
