apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: constant-deployment
    db: mongo
  name: constant-service
  namespace: ingress-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: constant-deployment
  type: ClusterIP
status:
  loadBalancer: {}
