apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: constant-service-entry
  name: constant-service-entry
spec:
  ports:
  - port: 8081
    protocol: TCP
    nodePort: 30002
  selector:
    app: constant-deployment
  type: NodePort
status:
  loadBalancer: {}
