apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: feature-service-entry
  name: feature-service-entry
spec:
  ports:
  - port: 8081
    protocol: TCP
    nodePort: 30003
  selector:
    app: feature-deployment
  type: NodePort
status:
  loadBalancer: {}
