apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: meeting-deployment
  name: meeting-service
  namespace: ingress-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: meeting-deployment
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: meeting-deployment
  name: meeting-service
  namespace: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: meeting-deployment
  type: ClusterIP
status:
  loadBalancer: {}
