apiVersion: v1
data:
  CORS: "https://henhaochi.io"
  SERVER_PORT: "8081"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: server-config
  namespace: ingress-nginx
---
apiVersion: v1
data:
  CORS: "http://localhost:3000"
  SERVER_PORT: "8081"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: server-config
  namespace: dev