apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db-service
  name: db-service
  namespace: staging
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 25060
  selector:
    db: sql
  type: ClusterIP
status:
  loadBalancer: {}