apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-controller
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT,GET,POST,OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://henhaochi.io"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Origin, Content-Type, Accept, filters"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
      - api.henhaochi.io
      secretName: echo-tls
  rules:
  - host: api.henhaochi.io
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80
      - path: /accounts
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80
      - path: /hashtags
        pathType: Prefix
        backend:
          service:
            name: constant-service
            port:
              number: 80
      - path: /features
        pathType: Prefix
        backend:
          service:
            name: feature-service
            port:
              number: 80
      - path: /posts
        pathType: Prefix
        backend:
          service:
            name: post-service
            port:
              number: 80
      - path: /meetings
        pathType: Prefix
        backend:
          service:
            name: meeting-service
            port:
              number: 80