apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongo-db-service
  name: mongo-db-service
  namespace: ingress-nginx
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 27017
  selector:
    db: mongo
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongo-db-service
  name: mongo-db-service
  namespace: dev
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 27017
  selector:
    db: mongo
  type: ClusterIP
status:
  loadBalancer: {}