apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongo-db-service
  name: mongo-db-service
  namespace: prod
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 27017
  selector:
    db: mongo
  type: ClusterIP
status:
  loadBalancer: {}