apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: post-deployment
  name: post-service
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: post-deployment
  type: ClusterIP
status:
  loadBalancer: {}