apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: constant-deployment
    db: mongo
  name: constant-deployment
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: constant-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: constant-deployment
        db: mongo
    spec:
      containers:
      - image: samueltyr/constant-service:0.0.1
        name: constant-deployment
        ports:
        - containerPort: 8081
        env:
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: DB_CONNECTION_STRING
        - name: SERVER_PORT
          valueFrom: 
            configMapKeyRef:
              name: server-config
              key: SERVER_PORT
        - name: CORS
          valueFrom: 
            configMapKeyRef:
              name: server-config
              key: CORS
        resources: {}
status: {}